### PR TITLE
updated Main.hx

### PR DESCRIPTION
**Pull request by lewislepton**
has the updated kha syntax bullshit. so now should work right away ;)

### CODE REVIEW

**Comment by ashes999** [comment]
I'm not working on this any more. But I'm curious to know why you're interested in this project.

**Comment by lewislepton** [comment]
i do kha teaching on youtube - https://www.youtube.com/c/lewislepton
sometimes i just find myself running into haxe/kha projects to look at & like to see how they work, if they work at all.
then if i fix it, [or remember that i have fixed ;)] ill then push it.

im just making sure that if others [mostly new users of kha & the curious] are searching online. randomly coming to projects made in haxe/kha, then they can use it right away & not feel discouraged.
since kha is more c++ type syntax, which is awesome in my eyes. but can be a bit 'hmmm?' for new flash folks ;)

plus i also like to learn better & more ways of coding that makes my life easier ;)
if something looks interesting i like to know about it ;)

**Comment by ashes999** [comment]
Thanks, I appreciate the help.

I've used Kha on and off for a couple of years. Two areas it majorly lacks are documentation (with specifics), and up-to-date, working examples. I would suggest looking into these two areas.

While blogs can suffice for docs, having up-to-date examples really needs to be done in tandem with production code-changes. You can't have someone not on the team doing this.

YouTube can cover both, but I can imagine someone finding your video a year from now and saying "this code no longer compiles," the same way I can find text tutorials from a year ago that no longer compile.

**Comment by lewislepton** [comment]
true. true.

i do try to keep most code updated. but do those in videos etc, talk about changes, so end up doing updates of the update ;)
i cant do text tutorials ;)

**Pull request merged**
